# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [31]:
import numpy as np

a = np.random.randint(100,size=6)
print('a:',a)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())

b = np.random.randint(100,size=12).reshape(2,3,2)
print('b:',b)
print('list(b): ', list(b))
print('tolist(): ', b.tolist())

#list只有用第一層，其他層數依舊會是ndarray type


a: [63 26 51 27 17  8]
list(a):  [63, 26, 51, 27, 17, 8]
tolist():  [63, 26, 51, 27, 17, 8]
b: [[[66 75]
  [71  5]
  [34  9]]

 [[57 63]
  [94 78]
  [49 69]]]
list(b):  [array([[66, 75],
       [71,  5],
       [34,  9]]), array([[57, 63],
       [94, 78],
       [49, 69]])]
tolist():  [[[66, 75], [71, 5], [34, 9]], [[57, 63], [94, 78], [49, 69]]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [32]:
# 記得先 Import 正確的套件

import numpy as np

In [33]:
a = np.random.randint(10, size=6) 
print('a:',a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

a: [1 8 9 4 8 2]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [34]:
a = np.random.randint(10, size=(3,4)) 

print('b:',a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

b: [[2 5 6 3]
 [2 4 6 6]
 [4 0 9 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [35]:
a = np.random.randint(10, size=(2,3,2)) 

print('c:',a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

c: [[[3 4]
  [0 6]
  [2 1]]

 [[2 9]
  [5 3]
  [6 1]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [36]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[2, 2, 9, 2, 2, 9]
[2, 2, 9, 2, 2, 9]


In [37]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[0, 3, 4, 7], [8, 0, 6, 8], [5, 0, 4, 0]]
[array([0, 3, 4, 7]), array([8, 0, 6, 8]), array([5, 0, 4, 0])]


In [38]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[8, 5], [4, 1], [0, 0]], [[0, 2], [4, 3], [2, 7]]]
[array([[8, 5],
       [4, 1],
       [0, 0]]), array([[0, 2],
       [4, 3],
       [2, 7]])]


In [41]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    
    newlist=[]
    for obj in iterable:
        newlist.append(tolist(obj))
    return newlist

    
print(tolist(a))
print(tolist(b))
print(tolist(c))


[2, 2, 9, 2, 2, 9]
[[0, 3, 4, 7], [8, 0, 6, 8], [5, 0, 4, 0]]
[[[8, 5], [4, 1], [0, 0]], [[0, 2], [4, 3], [2, 7]]]
